import type { Metadata } from "next";
import "./globals.css";
import 'leaflet/dist/leaflet.css';
import Provider from "@/Provider";
import ReduxUserProvider from "@/redux/ReduxUserProvider";
import Userdatafromredux from "@/Userdatafromredux";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <ReduxUserProvider>
            <Userdatafromredux/>
          {children}
          </ReduxUserProvider>
        </Provider>
      
      </body>
    </html>
  );
}
