import type { Metadata } from "next";
import "./globals.css";
import 'leaflet/dist/leaflet.css';
import Provider from "@/Provider";
import ReduxUserProvider from "@/redux/ReduxUserProvider";
import Userdatafromredux from "@/Userdatafromredux";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
  <body> 
    <Provider>
      <ReduxUserProvider>
        <Userdatafromredux />
          <main className="bg-white max-w-[1400px] mx-auto w-full px-4 sm:px-6 lg:px-8 min-h-screen">
          {children}
        </main>

      </ReduxUserProvider>
    </Provider>
  </body>
</html>
  );
}
